version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13
      - image: docker:stable-dind
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t simple-reverse-proxy .           
          environment:
            DOCKER_PASSWORD: $DOCKER_PASSWORD
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push adnananis/simple-reverse-proxy

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
